/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.loader;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f040027;
        public static final int font = 0x7f0400e6;
        public static final int fontProviderAuthority = 0x7f0400e8;
        public static final int fontProviderCerts = 0x7f0400e9;
        public static final int fontProviderFetchStrategy = 0x7f0400ea;
        public static final int fontProviderFetchTimeout = 0x7f0400eb;
        public static final int fontProviderPackage = 0x7f0400ec;
        public static final int fontProviderQuery = 0x7f0400ed;
        public static final int fontStyle = 0x7f0400ee;
        public static final int fontVariationSettings = 0x7f0400ef;
        public static final int fontWeight = 0x7f0400f0;
        public static final int ttcIndex = 0x7f040220;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f060077;
        public static final int notification_icon_bg_color = 0x7f060078;
        public static final int ripple_material_light = 0x7f060083;
        public static final int secondary_text_default_material_light = 0x7f060085;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f070050;
        public static final int compat_button_inset_vertical_material = 0x7f070051;
        public static final int compat_button_padding_horizontal_material = 0x7f070052;
        public static final int compat_button_padding_vertical_material = 0x7f070053;
        public static final int compat_control_corner_material = 0x7f070054;
        public static final int compat_notification_large_icon_max_height = 0x7f070055;
        public static final int compat_notification_large_icon_max_width = 0x7f070056;
        public static final int notification_action_icon_size = 0x7f0700c2;
        public static fina